FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /app 

COPY . .

RUN dotnet restore "FluxoCaixaDiario.sln"

WORKDIR "/app/src/FluxoCaixaDiario.Lancamentos"

RUN dotnet publish "FluxoCaixaDiario.Lancamentos.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS final
WORKDIR /app
EXPOSE 8080
EXPOSE 8081

COPY --from=build /app/publish .

ENTRYPOINT ["dotnet", "FluxoCaixaDiario.Lancamentos.dll"]